altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  6c548774-db85-4990-b2e2-0a03603c0679:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-02T07:49:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9b955a56-ea04-4f09-ad5e-79436a027baf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f5e5577-bba8-47a9-8265-d4ea0675c7e3
        userCondition: null
fs: formSubmissionImages
handle: formSubmissionAsset
name: 'Form Submission Asset'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
